# Generated by Django 5.2.1 on 2025-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=100)),
                ('last_name', models.CharField(help_text='enter your last name', max_length=100)),
                ('email', models.EmailField(help_text='enter your email address', max_length=50)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=10)),
            ],
        ),
    ]
